export const PREVIEW_BUCKET_LIST = [
  "Adopt a pet and provide it with a loving home",
  "Attend and present at a prestigious global medical conference (such as IEEE EMBC or RSNA)",
  "Attend the Day of the Dead festival in Mexico",
  "Attend the Olympics",
  "Be a vegetarian in 3 months",
  "Be accepted to a top-ranked hospital globally",
  "Be featured in Forbes 30 Under 30",
  "Be in a commercial",
  "Be part of a flash mob performance",
  "Become a parent",
  "Befriend someone from every continent",
  "Build an eco-friendly, self-sustaining but high-tech home",
  "Camp in a desert",
  "Can lead/have my own lab",
  "Climb Great Wall, China"
];

export const FULL_BUCKET_LIST = [
    ...PREVIEW_BUCKET_LIST,
    "Climb the Great Pyramid of Giza, Egypt",
    "Develop an AI-based diagnostic tool for respiratory diseases",
    "Eat at a 3 Michelin star restaurant, paid by my own money",
    "Fall in love",
    "Fly an airplane",
    "Free medical examination and treatment for underprivileged children",
    "Get a Green Card from EU",
    "Get a Professional Doctorate (Cardiology, Respiratory, or Psychology)",
    "Get published in the New Yorker",
    "Get to a dream university ranked in the Top 5 Globally",
    "Give a guest lecture at a world-renowned university",
    "Go camping with bestie",
    "Go on an African safari",
    "Graduate Bachelor and Master with high GPA",
    "Have 2 best friends who are always by my side",
    "Have a routine of doing yoga",
    "Have a small garden on the balcony of my house",
    "Have an album at the age of 18",
    "Invent a sensor that can help underserved people",
    "Join a scientific expedition to Antarctica",
    "Join and finish the Iron Man Marathon (Triathlon)",
    "Learn Japanese and visit Japan during the cherry blossom season",
    "Learn how to cook 1 signature dish from 20 cultures",
    "Learn Morse code and try communicating with someone using it",
    "Learn to dance hip-hop",
    "Learn to drive a car",
    "Learn to ski",
    "Live a month in a Buddhist temple",
    "Live in another country",
    "Master in Chinese",
    "Master in MATLAB and analysing biomedical graphics",
    "Master in coding Machine Learning and Deep Learning",
    "Master in cooking",
    "Master in designing pptx",
    "Master in makeup",
    "Master in playing Guitar (both Classic and Modern Music)",
    "Meet JK Rowling",
    "Meet Rick Riordan",
    "Meet Taylor Swift",
    "Participate in a Holi festival in India",
    "Publish 100 research papers",
    "Publish 3 Academic books",
    "Publish a fiction book (mainly about adventures)",
    "Reach the peak of 1 mountain",
    "Read 50 books/year",
    "Ride in a hot air balloon at sunrise",
    "See auroras",
    "Send a letter to my future self to be opened in 20 years",
    "Send a message to space (via a space mission or radio signal)",
    "Sleep in a castle",
    "Sleep outside on the beach, under the sky",
    "Solve a Rubik’s Cube in under 1 minute",
    "Speak at TED",
    "Spend a night in an underwater hotel",
    "Start a nonprofit organization",
    "Start a scholarship to support brave young kids",
    "Start a successful blog about my life",
    "Stay at an ice hotel and watch the Northern Lights",
    "Stay with an Amazonian tribe",
    "Take a walk in the rain singing a song",
    "Take a year off to travel the world",
    "Take refuge in the Three Jewels",
    "Teach a graduate-level course",
    "Transfer to 2 - 3 privileged universities during my studies",
    "Travel across Vietnam with my whole family",
    "Travel around Eastern Europe",
    "Travel around the US",
    "Travel to all 7 continents",
    "Travel to the Universal",
    "Try living without technology for a week",
    "Visit 100 countries",
    "Visit Googleplex",
    "Visit Silicon Valley",
    "Visit the Dead Sea and experience floating",
    "Visit the Seven Wonders of the World",
    "Volunteer 1000 hours to help the elderly",
    "Work as a medical volunteer in a war-torn region",
    "Write and send messages in a bottle, then release them into the ocean",
];
